dunstify -h string:x-dunst-stack-tag:sh "Press 1 for Shutdown"
dunstify -h string:x-dunst-stack-tag:hi "Press 2 for Hibernate"
dunstify -h string:x-dunst-stack-tag:su "Press 3 for Suspend"
dunstify -h string:x-dunst-stack-tag:re "Press 4 for Reboot"
dunstify -h string:x-dunst-stack-tag:ra "Press 5 for Ranczo 48 🐎"
dunstify -h string:x-dunst-stack-tag:rb "Press 6 for Ranczo 44 🐎"
dunstify -h string:x-dunst-stack-tag:rc "Press 7 for Ranczo 33 🐎"
dunstify -h string:x-dunst-stack-tag:ca "Press 8 to cancel"
